### ISSUE TITLE
Apparent incorrect saving of radio inputs

### ISSUE THREAD

**Issue by ETVO** [simsalabim/sisyphus#158]
Hello, everyone. I am not sure if anyone has yet presented the same problem, but I am facing some difficulties when saving data from radio inputs.

### My problem is, basically, this:

Having those 3 radio inputs:
`<input type="radio" name="test" value="one" id="test_one"> First`

`<input type="radio" name="test" value="two" id="test_two"> Second`

`<input type="radio" name="test" value="three" id="test_three"> Third`

When I check the FIRST, the SECOND, or the THIRD one, the action is saved successfully.
But if I checked the **THIRD**/**LAST** one, when I try to check any of the first two (or any other but the last, having more than 3 radio inputs), it keeps returning the THIRD as saved data.

### I mean:

**If I do this:**
- [x] First
- [ ] Second
- [ ] Third

**When I refresh/close-reopen:**
- [x] First
- [ ] Second
- [ ] Third
> everything's alright...

**If I do this:**
- [ ] First
- [ ] Second
- [x] Third

**When I refresh/close-reopen:**
- [ ] First
- [ ] Second
- [x] Third
> everything's alright, still

**BUT** if when I refresh/close-reopen I select another input, what looks like this:
- [ ] First
- [x] Second
- [ ] Third

or

- [x] First
- [ ] Second
- [ ] Third

**When I come back, it will be like this:**
- [ ] First
- [ ] Second
- [x] Third

## (Please don't mess my supposed-to-radio-button checkboxes)

Thank you very much for your time and patience.

**Comment by Kreyco** [comment]
Hi @ETVO You're right. I have a fixed in this PR #150 but I didn't generate the minified script, I thought Alexander would do it, but I'll do it and come with a new PR.

Thank you 😄

**Comment by ETVO** [comment]
Hello, Kreyco!
This is perfect, thanks very much!

Estevão Rolim

**Comment by Kreyco** [comment]
Hello @ETVO.
Sorry, I got really bussy the last month but I got a minified version. Would you try it out for me? Please.

Check out here:
https://github.com/Kreyco/sisyphus
b2624af88811f490d33f33cbd7ab673ebeee5b47

**Comment by haiyunx** [comment]
> Hello @ETVO.
> Sorry, I got really bussy the last month but I got a minified version. Would you try it out for me? Please.
> 
> Check out here:
> https://github.com/Kreyco/sisyphus
> [b2624af](https://github.com/simsalabim/sisyphus/commit/b2624af88811f490d33f33cbd7ab673ebeee5b47)

Hi Kreyco,

Thank you very much for the new push. I still see the problem on my end, but when I switch to unminified version, the problem disappeared.
